# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MLSpeechSynthesizer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MLSpeechSynthesizer
  target 'MLSpeechSynthesizerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MLSpeechSynthesizerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
